services:
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - task-tracker-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: ./env/Dockerfile
    depends_on:
      - postgres
    networks:
      - task-tracker-net
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: task_tracker
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

volumes:
  postgres_data:

networks:
  task-tracker-net:
    external: false
    name: task-tracker-net